title: OpenShift Design
url: "https://openshift.github.io"
baseurl: "/openshift-origin-design/"
# permalink: /:title
remote_theme: "pmarsceill/just-the-docs@v0.2.7"
# logo: "/assets/images/logo.png"
# defaults:
#   -
#     scope:
#       path: "designs"
#     values:
#       permalink: /:title
aux_links:
  "GitHub repo":
    - "//github.com/openshift/openshift-origin-design"
footer_content: "<a href=\"https://www.redhat.com/en/about/open-source\">Open Source</a> - <a href=\"https://github.com/openshift/openshift-origin-design/blob/master/LICENSE\">Apache License 2.0</a>"
# Footer metadata
show_last_edit_time: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
show_gh_edit_link: true
gh_edit_repository: "https://github.com/openshift/openshift-origin-design"
edit_link_text: "Edit this page on GitHub."